Add detailed cell renderer and group renderer
mercurymedia/elm-ag-grid pull request #7
Opened 2023-01-02 16:32 UTC by gouvermxt

2023-01-10 13:22 UTC, mschindlerMM requested changes

2023-01-10 13:22 UTC, mschindlerMM commented on src/AgGrid.elm
> +    | GroupRenderer (dataType -> String)
We should add some documentation about this "master-detail" feature. So people will know that we support this feature and how they can use it.

2023-01-10 13:22 UTC, mschindlerMM commented on src/AgGrid.elm
> +    , detailRenderer : Maybe { componentName : String, componentParams : Maybe Json.Encode.Value }
Let's try to keep values sorted. It's always helpful, especially when things get extended more and more.

2023-01-11 12:32 UTC, Tranquility approved these changes

2023-01-11 12:36 UTC, mschindlerMM approved these changes

2023-01-11 12:37 UTC, merged